declare const FP_HOMEPAGE: string;
declare const FP_BUILD_VERSION: string;
declare const FP_ENV: string;
declare const FP_DEBUG: boolean;
declare const TWEEN: any;
declare const PANOLENS: any;
declare const dashjs: any;
declare const Hls: any;
declare const WebVTT: any;
