declare const WWP_HOMEPAGE: string;
declare const WWP_BUILD_VERSION: string;
declare const WWP_ENV: string;
declare const WWP_DEBUG: boolean;
declare const TWEEN: any;
declare const PANOLENS: any;
declare const dashjs: any;
declare const Hls: any;
declare const WebVTT: any;
